package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.BuildType
import jetbrains.buildServer.configs.kotlin.v2018_2.buildSteps.powerShell
import jetbrains.buildServer.configs.kotlin.v2018_2.buildSteps.script
import jetbrains.buildServer.configs.kotlin.v2018_2.triggers.vcs
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'Build2'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, BuildType({
    id("Build2")
    name = "Build 2"

    params {
        param("my_new_parameter", "HOWDY!")
    }

    vcs {
        root(DslContext.settingsRoot)
    }

    steps {
        script {
            scriptContent = "call my_cmd.bat"
        }
        powerShell {
            name = "PowerShell"
            scriptMode = script {
                content = "${'$'}env:computername"
            }
        }
    }

    triggers {
        vcs {
        }
    }

    dependencies {
        snapshot(RelativeId("Build")) {
        }
    }
}))

